name: Maven CI/CD

on: [ push, pull_request ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: maven build and test
        run: mvn clean package
      - name: Upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: target/*.jar
      - name: Upload jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco

  build-docker-image:
    name: Docker Build and Deploy
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
#    if: ${{ contains(github.ref, 'master') }}
    steps:
      - uses: actions/checkout@v2
      - name: Download jar file
        uses: actions/download-artifact@v2
        with:
          name: app
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build --build-arg JAR_FILE=*.jar -t ${{ secrets.DOCKER_REPO }}:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}
